# Generated by Django 5.2.1 on 2025-05-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='raised',
        ),
    ]
